const PathNameMap = {
  '':'',
  '/':'',
  '/login':'登录',
  '/register':'注册',
  '/dashboard':'仪表盘',
  '/dashboard/home':'主页',
  '/dashboard/':'',
  '/dashboard/findcourses':'查找课程',
  '/dashboard/user/central':'用户中心',
  '/dashboard/ai-chat/:sessionId':'AI智能服务',
  '/dashboard/admin':'管理员主页',
  '/dashboard/admin/courses':'课程监控',
  '/dashboard/admin/users':'用户管理',
  '/dashboard/teacher/':'教师端主页',
  '/dashboard/teacher/courses':'我的课程',
  '/dashboard/teacher/questions':'教师题库',
  '/dashboard/student/':'学生端主页',
  '/dashboard/student/courses':'课程选择',
  '/dashboard/student/my-courses':'我的课程',
  '/dashboard/student/studentStatics':'学习情况',
}
export default PathNameMap;
