const PathNameMap = {
  '':'',
  '/':'',
  '/login':'登录',
  '/register':'注册',
  '/dashboard':'仪表盘',
  '/dashboard/main':'主页',
  '/dashboard/':'',
  '/dashboard/findcourses':'查找课程',
  '/dashboard/user/central':'用户中心',
  '/dashboard/aitalk/:sessionId':'AI智能服务',
  '/dashboard/admin':'管理员主页',
  '/dashboard/admin/class':'课程管理',
  '/dashboard/admin/users':'用户管理',
  '/dashboard/teacher/':'教师端主页',
  '/dashboard/teacher/class':'热门课程',
  '/dashboard/teacher/lessonScore':'课程成绩',
  '/dashboard/teacher/questionodteacher':'教师题库',
  '/dashboard/student/':'学生端主页',
  '/dashboard/student/class':'热门课程',
  '/dashboard/student/mycourse':'我的课程',
  '/dashboard/student/studentStatics':'学习情况',
}
export default PathNameMap;
