# spring 配置设置
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: your_password
    url: jdbc:mysql://localhost:3306/itap?useSSL=false&rewriteBatchedStatements=true
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 32
          max-idle: 16
          min-idle: 4
          max-wait: 2000ms
# web 服务设置
server:
  compression:
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
    enabled: true
  tomcat:
    threads:
      max: 200
      min-spare: 20
  port: 8080
  servlet:
    session:
      cookie:
        name: SESSION
        same-site: None
        secure: true
    context-path: /api
# 接口文档
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.cancan.usercenter
knife4j:
  enable: true
  setting:
    language: zh_cn
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
# 日志
logging:
  pattern:
    level: DEBUG
# 压力测试
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    enable:
      all: true
