name: Sync to Huawei Cloud

on:
  push:
    branches: main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub code
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --global user.name "Quixon-w"
        git config --global user.email "qxwang310@gmail.com"
        
        git remote add huaweicloud https://${{ secrets.HW_USERNAME }}:${{ secrets.HW_PASSWORD }}@codehub.codearts.huaweicloud.com/74e2063c952c45a4addaa62bfa9e31b8/ITAP.git

    - name: Push to Huawei Cloud
      run: |
        git push --force huaweicloud HEAD:main
